# Generated by Django 5.1.1 on 2024-10-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_categoria_created_remove_categoria_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
